name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    branches:
      - main

jobs:
  gateway:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/gateway
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Clean Up
        run: rm ../../package.json
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - name: Check Formatting
        run: npm run prettier
      - name: Docker Tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            hicsail/harbor-gateway
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push Docker Build
        uses: docker/build-push-action@v4
        with:
          context: ./packages/gateway
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}'
          cache-from: type=gha
          cache-to: type=gha,mode=max
  client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/client
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Clean Up
        run: rm ../../package.json
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - name: Check Formatting
        run: npm run prettier
      - name: Docker Tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            hicsail/harbor-client
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push Docker Build
        uses: docker/build-push-action@v4
        with:
          context: ./packages/client
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deployment:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    needs: [gateway, client]
    steps:
      - name: Push to Staging
        uses: fjogeleit/http-request-action@v1
        with:
          method: "POST"
          url: ${{ secrets.PORTAINER_WEBHOOK_STAGING }}
          preventFailureOnNoResponse: true
      - name: Push to Production
        uses: fjogeleit/http-request-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          method: "POST"
          url: ${{ secrets.PORTAINER_WEBHOOK_PRODUCTION }}
          preventFailureOnNoResponse: true
  review-app:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    needs: client
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate port number
        id: port
        run: echo "::set-output name=port::$(( 10000 + ${{ github.event.pull_request.number }} ))"
      - name: Create Review App
        uses: LGinC/portainer-stack-deploy@master
        with:
          serverurl: "https://port.sail.codes"
          endpointId: 3
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          stackname: "harbor-client-review-${{ github.event.pull_request.number }}"
          variables: |
            port=${{ steps.port.outputs.port }}
            tag=pr-${{ github.event.pull_request.number }}
          docker_compose: |
            version: '3.8'
            services:
              harbor-client:
                container_name: harbor-client-{{ tag }}
                image: hicsail/harbor-client:{{ tag }}
                restart: always
                ports:
                  - {{ port }}:80
      - name: Post Comment
        uses: mshick/add-pr-comment@v2
        with:
          message: Review App Hosted Here [http://199.94.60.241:${{ steps.port.outputs.port }}](http://199.94.60.241:${{ steps.port.outputs.port })