name: delete review app
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  delete-review-app:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Review App
        uses: kgierke/portainer-stack-deployment@v1
        with:
          portainer-url: "https://port.sail.codes"
          portainer-endpoint: 3
          portainer-username: ${{ secrets.PORTAINER_USERNAME }}
          portainer-password: ${{ secrets.PORTAINER_PASSWORD }}
          name: "harbor-client-review-${{ github.event.pull_request.number }}"
          file: deployment/review.yml
          delete: true